language: node_js
node_js:
  - "0.10"
services:
  - mongodb
  - redis-server
notifications:
  email: false
script:
  - npm run syntax
  - npm test
after_script:
  - npm run coveralls

env:
  global:
    - DEBUG=0
    - secure: "gGfP672dPQCkb0eSSqX5AKQEA9R1CtlHus8ZSnNBO778j8TkL89n76vIfF2ohW9ADmGlRemB/fKC0ReRd6+eNHx9ZLUXi4hrQ0KZXfE3Ym6UJs4jez4BUnLfSqkkEsImXVCZo6Ox37ZS6F1J6xpiRC3Vqlke7C97ZlsBZaMRQcc="
    - secure: "HtyeoeoceMrsg+W6+uhy2K4gXJ619l0lWnuIjco50ej+TDLWl/PyyBPJh90VfxfUIWIKutr5EqBNq45OLNPa5mXP+Pmm1WE/RCxnqnS8xaF9r54fiHj6nxEfDkK4VGdrMOKNT0tt6ELdTqKqsU25C8CCQKcU3RZo0+BxEgeo6A8="
    - secure: "Vc3TSc4rkFdBUEyOJ5Zam3JAEe1AP1q82gSROVh9VIcw2cwK7diVggxRYQlN7LrEzNgVGcdPfHQmNyVyiqK9L6nd2tcDkmJztcser8qnbLKOYAnlRo7zgEJf3J1gLgM83F5zu76mE0tQJrfe+OF5s9B9J5woPwAC8J5rgmn2BZI="
    - secure: "T2JEcRZpJtsrvO3cYfJwBoQPlaxWP/UTHmZ89aoBf3kH3u7mqcDPNawvBI+qLYKqEXTHewo4k5+kFNKxX50UBvArP8NDpdjFU9zSNfw+SefIWGKFVjBSnUpNiK2e5y1glriepC1Th1LGWzwlm3DmVc7cprcIWGUabiWVuR25uac="
